title: tobiasbusch.xyz
baseURL: /
params:
  description: A portfolio theme with a blog
  color_scheme: light
  accent_color: pink
  header:
    title: tobiasbusch.xyz
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Blog
        url: /blog/
        style: link
      - label: Portfolio
        url: /portfolio/
        style: link
      - label: About Me
        url: /about/
        style: link
      - label: Contact
        url: /contact/
        style: link
    logo_img: images/favicon.png
  footer:
    content: >-
      &copy; Tobias Busch. This site is powered by <a
      href="https://www.stackbit.com" target="_blank" rel="noopener">Stackbit.
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/'
        style: icon
        icon_class: fa-twitter
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: fa-instagram
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: icon
        icon_class: fa-linkedin
        new_window: true
      - label: Github
        url: lorem-ipsum
        style: icon
        icon_class: fa-github
        new_window: false
        type: action
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
